### ISSUE TITLE
Synchronization between Axelar and Swing

### ISSUE THREAD

**Issue by dobertRowneySr** [danielssonn/ethTO#14]
I have written down a couple of ideas

- Lender on Moonbeam lists NFT at `(address, id)` on the marketplace with `payment` and `collateral` info and a `maximum_rent_period`
~LIsting happens on all supported chain (or a subset of them if the lender wants to avoid posting the rent on certain chains) , suppose the rent is listed on Polygon~. Listing happens only on renter chain.
- Renter on Polygon wants to rent NFT at `(address, id)` starting immediately for given `period` by providing `payment` and `collateral`

#### Protocol 1
This protocol is implemented at the dApp level and not at the smart contract level, since we need to use swing.xyz sdk
1. dApp calls the `can_rent` smart contract function which checks conditions on `period`, `payment`, `collateral` are satisfied. No mutation is performed. This function will be marked as `view` so no gas are spent by the renter
2. Renter sends payment with swing xyz, and waits for a `SUCCESS` status [see](https://apidoc.dev.swing.xyz/docs/swing-sdk/5io6kxpn3ozii-start-a-transfer)
3. dApp will call the `rent` function and update the listing as rented on the `renter` chain
4. Axelar Executor will then take care of calling the `lend` function on the `lender` chain updating the status

#### Issues
- What if 2 succeeds and 3-4 fails?
- is this introducing an oracle (swing.xyz) ?
- if we go this route why do we even need axelar since we can the `lend` function at the dApp level

#### Protocol 2
We keep the current smart contract setup
1. Renter swap tokens via swing into the preferred token on the listings (which has to be transferrable using Axelar)
2. dApp will call  the `rent` function on the renter chain  which checks conditions on : 
 - `nft` is available for rent
 - `period`
 - `payment`
 -  `collateral` are satisfied
 And sends the tokens via the Axelar network
4. On the lender chain the `lent` function is invoked by the Axelar executor updating the listing (hence the listing gets updated only one time)

#### Pros
- the funds belongs to the lender no matter what
- no cross chain oracles used, just Axelar
- No need to update all listings

*Updated* on Fri 5 Aug 2022, 2:35 pm EDT

**Comment by danielssonn** [comment]
I like it a lot. The protocol 2 looks more appealing from afar, I wonder if there's a UX difference (number of approvals required, total gas spent etc.) between the two. I used to think the NFT would be only posted on lender's home chain. If we list it on multiple chains concurrently, can we get into a race condition where multiple renters try to grab the same NFT around the same time from two different chains?

**Comment by mattxyzeth** [comment]
I'm also wondering about the race condition and it might be gas intensive to update every chain the NFT listing is posted on so Protocol 2 seems to be a better way to go. The use of Swing.xyz would come into play when the lender collects the payment. Should we then have a mechanism that doesn't immediately send the payment to the lender but waits for the lender to collect?

**Comment by mattxyzeth** [comment]
One issue I see though is that Swing only supports certain tokens. So it would have limited support for wrapped tokens. Can Axelar swap native tokens instead of wrapping?

**Comment by dobertRowneySr** [comment]
>  can we get into a race condition where multiple renters try to grab the same NFT around the same time from two different chains?

Yes good catch, plus I overlooked the fact that we need to update all the listing on every chains the NFT is listed on.
This is not feasible in terms of gas fees.

**Comment by dobertRowneySr** [comment]
this has been modified and merged.
