### ISSUE TITLE
Axelar contract explainer

### ISSUE THREAD

**Issue by dobertRowneySr** [danielssonn/ethTO#8]
The demo will showcase some Polygon and Moonbeam native NFTs.
We will deploy the NFT marketplace contract on both Moonbeam and Polygon
We will also deploy the same contract [Axelar executor contract ](https://github.com/axelarnetwork/axelar-local-gmp-examples/blob/main/examples/call-contract/ExecutableSample.sol) on both chains
```mermaid
flowchart TB
subgraph polygon
    Polygon_Native_NFTs
    Polygon_Native_NFT_marketplace 
    subgraph Polygon_Axelar_Executor_contract
    end
end
subgraph moonbeam
    Moonbeam_Native_NFTs
    Moonbeam_Native_NFT_marketplace 
    subgraph Moonbeam_Axelar_Executor_contract
    end
end
Polygon_Axelar_Executor_contract ---|Axelar_Network|Moonbeam_Axelar_Executor_contract
```

## Use case
Suppose I am a user accessing in the Polygon marketplace and I am interested in renting a particular Moonbeam native NFT listed.
I will call the `rent(` function via the dApp which will:
1. call the  `Polygon_Axelar_executor` contract on Polygon (Source chain) which in turn it will 
    - call`rentOnAlternativeChain(..)` on Polygon in order to check rent preconditions and then locking the collateral and marking the NFT as rented
    - setup the gas fees on Polygon via `gasReceiver.payNativeGasForContractCall`
    - send the TX together with the `payaload` and the payment amount to the axelar network via  [` gateway().callContractwithToken(..)`](https://docs.axelar.dev/dev/build/gmp-tokens-with-messages)
 2.  The TX will be send to the Axelar network and after it is confirmed by its validator it will be redirected to the Polygon gateway
 3. The Tx reaches the Moonbeam network (Destination chain) where it will be automatically confirmed and executed. The execution part consists in invoking the `_execute` function on `Moonbeam_Axelar_Executor_contract` which will:
    - pay the total amount for the rent to the `lender` 
    - call `rentOnNativeChain(..)` on Moonbeam which effectively marks the NFT as rented on the Moonbeam chain and 
      transfers the NFT from the markeplace address to the renter account on Moonbeam

*Updated* , 2022.08.04, 1:49 PM EDT

**Comment by danielssonn** [comment]
Can we callContact( ..., withTokens) that we can use for methods that require a payment or collateral - payable methods in general? What would the flow look like, and what would happen to the tokens on both source and destination chains?

**Comment by mattxyzeth** [comment]
One question I have is regarding the feature we're offering to allow the payment and collateral to be in any currency. The way it works is that the contract interacts with the ERC-20 on the chain that the contract is deployed. In this scenario where our `NFTMarket` contract is deployed on Moonbeam, that contract would only be able to interact with ERC-20 tokens on the Moonbeam network. We'll have to set some limitations to ensure the lender can only choose a token on the chain the NFT is deployed on.

**Comment by mattxyzeth** [comment]
If there was a way we could also wrap an ERC-20 token from one chain and use it on another, we could solve this issue in a roundabout way.

**Comment by dobertRowneySr** [comment]
## Details about token transfer on Axelar
- we can list the NFT say in MATIC  on Polygon but payment in matic from Polygon --> Moonbeam has to use wMATIC (using the example above as reference). Axelar takes a fees on top each token transfer depending on token, destination chain and source chain https://docs.axelar.dev/resources/testnet (testnet calculator)
